[package]
name = "iotacoin"
version = "0.1.0"
authors = ["Kevin Del Castillo <quebin31@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
num-bigint = "0.3"
num-integer = "0.1"
num-traits = "0.2"
thiserror = "1"
try-block = "0.1.0"
